- name: create folders
  file:
    path: /home/ubuntu/go/src/github.com/juankis/registry
    state: directory
    mode: 0777

- name: install driver mysql
  shell: "/usr/local/go/bin/go get github.com/go-sql-driver/mysql"
  
- name: install connector mysql
  shell: "/usr/local/go/bin/go get github.com/jmoiron/sqlx"
  
- name: install gin
  shell: "/usr/local/go/bin/go get github.com/gin-gonic/gin"
  
- name: git clone registry
  git:
    repo: 'https://github.com/juankis/registry'
    dest: /home/ubuntu/go/src/github.com/juankis/registry
    clone: yes
    update: yes

- name: go run 
  shell: "(cd /; /usr/local/go/bin/go run /home/ubuntu/go/src/github.com/juankis/registry/api/src/main/main.go >/dev/null 2>&1 &)"
  async: 10
  poll: 0  